---
title: Assignment 2
author: Author1, Author2, Author3, Author4
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
---
```{r include = FALSE}
# Disable inclusion of code chunks in the output
knitr::opts_chunk$set(echo = FALSE)
library('ggplot2')
```


# 1

## Stationary and non-invertible
Roots of $\theta(z^-1)$ are around $0.412$ and $-1.212$. Not invertible.
Root of $\phi(z^-1)$ is $4/5$. Stationary.

## Two first central moments
Because it is stationary, 
the mean and autocovariance function must be invariant to absolute time.

\begin{align*}
  E( X_{t}) & =E( 0.8X_{t-1} +\epsilon _{t} +0.8\epsilon _{t-1} -0.5\epsilon _{t-2})\\
  & =0.8E( X_{t-1})\\
  & =0.8E( X_{t})\\
  & =0
\end{align*}


From (Eq. 5.98)
\begin{align*}
  \gamma _{\epsilon X}( 0) & =\theta _{0} \sigma _{\epsilon }^{2}\\
  \gamma _{\epsilon X}( 1) & =( \theta _{1} -\phi _{1} \theta _{0}) \sigma _{\epsilon }^{2}\\
  & \\
  \gamma _{\epsilon X}( 2) +\phi _{1} \gamma _{\epsilon X}( 1) & =\theta _{2} \sigma _{\epsilon }^{2}\\
  \gamma _{\epsilon X}( 2) & =\theta _{2} \sigma _{\epsilon }^{2} -\phi _{1}( \theta _{1} -\phi _{1} \theta _{0}) \sigma _{\epsilon }^{2}\\
  & =\left( \theta _{2} -\phi _{1} \theta _{1} +\phi _{1}^{2} \theta _{0}\right) \sigma _{\epsilon }^{2}
\end{align*}

From (Eq. 5.99), recall that $\displaystyle \gamma ( -1) =\gamma ( 1)$, since it is an even function.
\begin{equation*}
\begin{aligned}
  \gamma ( k) +\phi _{1} \gamma ( k-1) & =\theta _{k} \gamma _{\epsilon X}( k) +\theta _{k+1} \gamma _{\epsilon X}( k+1) +\theta _{2} \gamma _{\epsilon X}( q-k)\\
  & \\
  \gamma ( 0) +\phi _{1} \gamma ( 1) & =\theta _{0} \gamma _{\epsilon X}( 0) +\theta _{1} \gamma _{\epsilon X}( 1) +\theta _{2} \gamma _{\epsilon X}( 2)\\
  \gamma ( 1) +\phi _{1} \gamma ( 0) & =\theta _{1} \gamma _{\epsilon X}( 0) +\theta _{2} \gamma _{\epsilon X}( 1)\\
  \gamma ( 2) +\phi _{1} \gamma ( 1) & =\theta _{2} \gamma _{\epsilon X}( 0)
\end{aligned}
\end{equation*}

From (Eq. 5.101)
\begin{align*}
  \gamma ( 3) +\phi _{1} \gamma ( 2) & =0\\
  \gamma ( k) & =-\phi _{1} \gamma ( k-1) ,\ \forall k\geqslant 3
\end{align*}

Solve for $\displaystyle 0\leqslant k\leqslant 2$ with Maple.
```
p1 := -0.8:
q1 := 0.8:
q2 := -0.5:

s := 0.4^2:
ye0 := s:
ye1 := (q1 - p1)*s:
ye2 := (q2 - p1*q1 + p1^2)*s:

solve({
  p1*y1 + y0 = q1*ye1 + q2*ye2 + ye0, 
  p1*y0 + y1 = q1*ye0 + q2*ye1, 
  p1*y1 + y2 = q2*ye0}, 
  {y0, y1, y2}
);
```

Which results in
```
{y0 = 0.8400000000, y1 = 0.6720000000, y2 = 0.4576000000}
```


## Simulation 10
```{R}
n_obs <- 200
n_sim <- 10

sigma <- 0.4

phi <- c(-0.8)
p <- length(phi)

theta <- c(0.8, -0.5)
q <- length(theta)

X_sim <- replicate(n_sim, {
  # Create noise
  epsilon <- rnorm(n_obs + q, 0, sigma)

  # Create vector for X
  X <- rep(0, n_obs)

  for (t in seq(2, n_obs)) {
    X[t] <- -phi[1] * X[t - 1] + epsilon[t + q] + theta[1] * epsilon[t + q - 1] + theta[2] * epsilon[t + q - 2]
  }

  # Return X
  X
})


# Plot all simulations
# plot.ts(X_sim)
# Plot all simulations

sim_plot <- ggplot(mapping = aes(x = seq(1, n_obs))) +
  labs(x = "Time", y = "X")

for (i in seq(1, n_sim)) {
  sim_plot <- local({
    j <- i
    sim_plot +
      geom_line(aes(y = X_sim[, j]), stat = "identity", alpha = 0.9, col = j)
      # + geom_point(aes(y = X_sim[, j]), stat = "identity", alpha = 0.3, col = j)
  })
}

sim_plot
```

## ACF
```{R}
n_lag <- 40

# Empirical ACF
acf_matrix <- matrix(0, nrow = n_lag+1, ncol = n_sim)
for (i in seq(1, n_sim)) {
  acf_matrix[, i] <- acf(X_sim[, i], lag.max = n_lag, type = c("correlation"), plot = FALSE)$acf
}

# Theoretical ACF
acf_theo <- rep(0, n_lag + 1)
acf_theo[1] <- 0.84
acf_theo[2] <- 0.672
acf_theo[3] <- 0.4576
for (k in seq(3, n_lag)) {
  acf_theo[k + 1] <- -phi[1] * acf_theo[k]
}

acf_theo <- acf_theo / acf_theo[1]


# Plot
# NOTE: Significance level from 
acf_sig_level <- qnorm((1 + 0.95) / 2) / sqrt(sum(!is.na(X_sim[, 1])))


acf_plot <- ggplot(mapping = aes(x = seq(0, n_lag)))

for (i in seq(1, n_sim)) {
  acf_plot <- local({
    j <- i
    acf_plot +
      geom_line(aes(y = acf_matrix[, j]), stat = "identity", alpha = 0.2, col = j) +
      geom_point(aes(y = acf_matrix[, j]), stat = "identity", alpha = 0.3, col = j)
  })
}

acf_plot <- acf_plot +
  geom_hline(yintercept = acf_sig_level, linetype = "dotted") +
  geom_hline(yintercept = -acf_sig_level, linetype = "dotted") + 
  geom_line(aes(y = acf_theo), stat = "identity", color = "blue") +
  geom_point(aes(y = acf_theo), stat = "identity", color = "blue") +
  labs(title = "ACF", x = "Lag", y = "ACF")

acf_plot
```

## PACF
```{R}
pacf_matrix <- matrix(0, nrow = n_lag, ncol = n_sim)
for (i in seq(1, n_sim)) {
  pacf_matrix[, i] <- pacf(X_sim[, i], lag.max = n_lag, type = c("correlation"), plot = FALSE)$acf
}


pacf_plot <- ggplot(mapping = aes(x = seq(1, n_lag)))

for (i in seq(1, n_sim)) {
  pacf_plot <- local({
    j <- i
    pacf_plot +
      geom_line(aes(y = pacf_matrix[, j]), stat = "identity", col = j) +
      geom_point(aes(y = pacf_matrix[, j]), stat = "identity", col = j)
  })
}

pacf_plot <- pacf_plot +
  geom_hline(yintercept = acf_sig_level, linetype = "dotted") +
  geom_hline(yintercept = -acf_sig_level, linetype = "dotted") + 
  labs(title = "PACF", x = "Lag", y = "PACF")

pacf_plot
```

## Variance
```{R}
X_sim_var <- apply(X_sim, 2, var)

var_plot <- ggplot(mapping = aes(x = seq(1, n_sim), y = X_sim_var)) +
  geom_bar(stat = "identity", fill = 1:n_sim) +
  geom_hline(yintercept = 0.84, col = "blue") +
  geom_hline(yintercept = mean(X_sim_var), linetype = "dotted") +
  labs(title = "Variance", x = "Simulation", y = "Variance")

var_plot
```


## Discussion


# 2


# 3